import "server-only";

/**
 * Server-side branded PDF generation.
 *
 * Locally we return the print-ready HTML (the browser's "Save as PDF"
 * finishes the job) and the client opens it. In a Catalyst deployment,
 * setting CATALYST_SMARTBROWZ_URL + CATALYST_SMARTBROWZ_KEY routes the
 * same HTML through Catalyst SmartBrowz (headless Chromium) to produce a
 * real server-generated PDF binary — no code change at the call site.
 */

export function smartBrowzConfigured(): boolean {
  return !!(process.env.CATALYST_SMARTBROWZ_URL && process.env.CATALYST_SMARTBROWZ_KEY);
}

/**
 * Convert branded HTML to a PDF via Catalyst SmartBrowz when configured.
 * Returns null locally (caller falls back to serving HTML for print-to-PDF).
 */
export async function htmlToPdf(html: string): Promise<Buffer | null> {
  if (!smartBrowzConfigured()) return null;
  try {
    const res = await fetch(process.env.CATALYST_SMARTBROWZ_URL as string, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Zoho-oauthtoken ${process.env.CATALYST_SMARTBROWZ_KEY}`,
      },
      body: JSON.stringify({ html, output: "pdf", page: { format: "A4", margin: "18mm" } }),
    });
    if (!res.ok) return null;
    return Buffer.from(await res.arrayBuffer());
  } catch {
    return null;
  }
}

/** A4 print-optimized, KSP-branded standalone HTML document. */
export function brandedReportHtml(opts: {
  title: string;
  generatedOn: string;
  sections: { heading: string; rows: (string | number)[][]; columns: string[] }[];
  summary: [string, string | number][];
}): string {
  const summaryCells = opts.summary
    .map(([l, v]) => `<div class="tile"><div class="tl">${esc(l)}</div><div class="tv">${esc(String(v))}</div></div>`)
    .join("");
  const sections = opts.sections
    .map(
      (s) => `
      <section>
        <h3>${esc(s.heading)}</h3>
        <table>
          <thead><tr>${s.columns.map((c) => `<th>${esc(c)}</th>`).join("")}</tr></thead>
          <tbody>${s.rows
            .map((r) => `<tr>${r.map((c) => `<td>${esc(String(c))}</td>`).join("")}</tr>`)
            .join("")}</tbody>
        </table>
      </section>`
    )
    .join("");

  return `<!doctype html><html lang="en"><head><meta charset="utf-8"/>
  <title>${esc(opts.title)} — NETRA</title>
  <style>
    * { box-sizing: border-box; }
    body { font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #111; margin: 0; padding: 32px 40px; }
    .head { display:flex; justify-content:space-between; align-items:flex-start; border-bottom: 3px solid #0f766e; padding-bottom: 14px; }
    .brand { display:flex; align-items:center; gap:10px; }
    .logo { width:34px; height:34px; border-radius:8px; background:#0f766e; color:#fff; display:grid; place-items:center; font-weight:800; }
    .org { font-size: 12px; color:#555; letter-spacing:.03em; text-transform:uppercase; }
    h1 { font-size: 22px; margin: 6px 0 2px; }
    .meta { font-size: 12px; color:#666; }
    .conf { border:1px solid #b91c1c; color:#b91c1c; font-size:11px; font-weight:700; padding:4px 8px; border-radius:6px; letter-spacing:.05em; }
    .tiles { display:flex; gap:12px; margin: 20px 0; }
    .tile { flex:1; border:1px solid #ddd; border-radius:8px; padding:10px 12px; }
    .tl { font-size:10px; text-transform:uppercase; color:#777; letter-spacing:.04em; }
    .tv { font-size:22px; font-weight:800; }
    section { margin-top: 22px; page-break-inside: avoid; }
    h3 { font-size: 14px; margin: 0 0 8px; color:#0f766e; }
    table { width:100%; border-collapse: collapse; font-size: 12px; }
    th { text-align:left; color:#555; border-bottom:1.5px solid #ccc; padding:6px 8px; font-size:11px; }
    td { padding:6px 8px; border-bottom:1px solid #eee; }
    footer { margin-top: 28px; border-top:1px solid #ddd; padding-top:10px; font-size:10px; color:#888; }
    @media print { body { padding: 0; } }
  </style></head>
  <body>
    <div class="head">
      <div>
        <div class="brand"><span class="logo">N</span><span class="org">NETRA · State Crime Records Bureau</span></div>
        <h1>${esc(opts.title)}</h1>
        <div class="meta">Karnataka State Police · Generated ${esc(opts.generatedOn)}</div>
      </div>
      <span class="conf">CONFIDENTIAL</span>
    </div>
    <div class="tiles">${summaryCells}</div>
    ${sections}
    <footer>Generated by NETRA AI · Every figure is derived from audited crime records (official CaseMaster schema). For authorized law-enforcement use only.</footer>
  </body></html>`;
}

function esc(s: string): string {
  return s.replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c] as string));
}
