"use client";
import { useState, useRef, useEffect, useCallback } from "react";
import { useSearchParams } from "next/navigation";
import {
  Sparkles, Send, Database, ChevronDown, ShieldCheck, Lightbulb, User, CornerDownLeft, Loader2,
  Mic, MicOff, Volume2, FileDown, History, Cpu, Route, ScanText,
  UserSearch, Network as NetworkIcon, Flame, GitCompare, Users,
} from "lucide-react";
import type { AiInsight } from "@/lib/types";
import { TrendLine, BarSeries } from "@/components/charts";
import { cn } from "@/lib/utils";
import { useAppStore } from "@/store/useAppStore";
import { useT } from "@/lib/i18n-client";
import { askAssistant, askRag, aiConfigured, translateText, synthesizeSpeech, analyzeVoiceCommand, transcribeAudio, extractText, type RagSource } from "@/lib/ai-client";
import { Translated } from "@/components/Translated";
import { Badge } from "@/components/ui";

const NETRA_SYSTEM =
  "You are NETRA, an AI crime-investigation assistant for the Karnataka State Police. " +
  "Answer the officer's question clearly and concisely. If the question needs specific case " +
  "records you do not have, say so and suggest where in NETRA to look (cases, criminals, network, maps).";

/** Build an AiInsight shell around a plain-text answer from the Catalyst Function. */
function textInsight(answer: string, source: AiInsight["explain"]["source"]): AiInsight {
  return {
    answer,
    explain: {
      confidence: source === "llm" ? 0.82 : 0.4,
      reasoning: source === "llm" ? "Generated by Zoho Catalyst QuickML." : "AI backend not connected in this build.",
      records_used: 0,
      evidence: [],
      alternatives: [],
      source,
      audit_id: `A-${Date.now().toString(36).toUpperCase()}`,
      processing_ms: 0,
      ai_model: source === "llm" ? "VL-Qwen3.6-35B-A3B" : "none",
    },
  };
}

/** Build an AiInsight from a RAG answer + the case documents it was grounded on. */
function ragInsight(answer: string, sources: RagSource[]): AiInsight {
  const evidence = sources
    .map((s) => (s.title || s.snippet || "").toString().slice(0, 80))
    .filter(Boolean)
    .slice(0, 8);
  return {
    answer,
    explain: {
      confidence: 0.85,
      reasoning: sources.length
        ? `Grounded in ${sources.length} case document${sources.length === 1 ? "" : "s"} retrieved from the knowledge base by Zoho Catalyst QuickML RAG.`
        : "Answered by Zoho Catalyst QuickML RAG (no source passages returned).",
      records_used: sources.length,
      evidence,
      alternatives: [],
      source: "rag",
      audit_id: `A-${Date.now().toString(36).toUpperCase()}`,
      processing_ms: 0,
      ai_model: "rag",
    },
  };
}

interface Turn {
  id: number;
  q: string;
  insight?: AiInsight;
  loading?: boolean;
}

// Queries that hit the QuickML RAG knowledge base (the uploaded case dossiers).
const EXAMPLES = [
  "What crimes are recorded in the case files?",
  "Summarise the burglary cases and the accused",
  "Tell me about the cybercrime OTP fraud case",
  "Which cases involve vehicle theft?",
  "What evidence was collected in these cases?",
];

const SOURCE_LABEL: Record<string, string> = {
  "template-sql": "Verified SQL",
  llm: "Catalyst QuickML",
  rag: "Catalyst QuickML · RAG",
  cache: "Cache",
  "demo-engine": "Keyword search",
  semantic: "Semantic search",
  lookup: "Database dossier",
};

// One-click prompts, each grounded in the RAG knowledge base (case dossiers).
const TASKS: { icon: typeof UserSearch; label: string; q: string }[] = [
  { icon: Flame, label: "All crimes", q: "What crimes are recorded in the case files?" },
  { icon: UserSearch, label: "Burglary", q: "Summarise the burglary cases and the accused" },
  { icon: NetworkIcon, label: "Cybercrime", q: "Tell me about the cybercrime OTP fraud case" },
  { icon: GitCompare, label: "Vehicle theft", q: "Which cases involve vehicle theft?" },
  { icon: Users, label: "Evidence", q: "What evidence was collected in these cases?" },
];

// Friendly label for the engine that handled a query (option C — smart routing).
const ROUTE_LABEL: Record<string, string> = {
  "rule-engine": "rule-engine (local · instant)",
  "tfidf-embeddings": "semantic index (local)",
  "db-lookup": "database lookup (local)",
  fallback: "keyword fallback (local)",
};
function routeLabel(model: string): string {
  if (ROUTE_LABEL[model]) return ROUTE_LABEL[model];
  if (/rag/i.test(model)) return "Catalyst QuickML · RAG";
  return `Catalyst QuickML · ${model}`;
}

/* Minimal typings for the Web Speech API (not in TS dom lib everywhere). */
type SpeechRecognitionLike = {
  lang: string;
  interimResults: boolean;
  continuous: boolean;
  onresult: ((e: { results: ArrayLike<ArrayLike<{ transcript: string }> & { isFinal: boolean }> }) => void) | null;
  onend: (() => void) | null;
  onerror: ((e?: { error?: string }) => void) | null;
  start: () => void;
  stop: () => void;
};

const SPEECH_ERR: Record<string, string> = {
  "not-allowed": "Microphone permission denied — allow mic access in the browser.",
  "service-not-allowed": "Microphone permission denied — allow mic access in the browser.",
  "no-speech": "No speech detected — try again and speak clearly.",
  "audio-capture": "No microphone found.",
  "language-not-supported": "This browser can't recognise the selected language. Switch to English or use Chrome.",
  "network": "Network error reaching the speech service.",
};
function speechErr(code?: string): string {
  return SPEECH_ERR[code || ""] || "Voice input failed — try Chrome, or deploy the Catalyst Zia path.";
}

function getSpeechRecognition(): (new () => SpeechRecognitionLike) | null {
  if (typeof window === "undefined") return null;
  const w = window as unknown as Record<string, unknown>;
  return (w.SpeechRecognition || w.webkitSpeechRecognition) as (new () => SpeechRecognitionLike) | null;
}

function getAudioContext(): typeof AudioContext | null {
  if (typeof window === "undefined") return null;
  const w = window as typeof window & { webkitAudioContext?: typeof AudioContext };
  return window.AudioContext || w.webkitAudioContext || null;
}

function encodeMonoWav(samples: Float32Array, sampleRate: number): Blob {
  const buffer = new ArrayBuffer(44 + samples.length * 2);
  const view = new DataView(buffer);
  const write = (offset: number, value: string) => {
    for (let i = 0; i < value.length; i += 1) view.setUint8(offset + i, value.charCodeAt(i));
  };
  write(0, "RIFF");
  view.setUint32(4, 36 + samples.length * 2, true);
  write(8, "WAVE");
  write(12, "fmt ");
  view.setUint32(16, 16, true);
  view.setUint16(20, 1, true);
  view.setUint16(22, 1, true);
  view.setUint32(24, sampleRate, true);
  view.setUint32(28, sampleRate * 2, true);
  view.setUint16(32, 2, true);
  view.setUint16(34, 16, true);
  write(36, "data");
  view.setUint32(40, samples.length * 2, true);
  let offset = 44;
  for (let i = 0; i < samples.length; i += 1, offset += 2) {
    const sample = Math.max(-1, Math.min(1, samples[i]));
    view.setInt16(offset, sample < 0 ? sample * 0x8000 : sample * 0x7fff, true);
  }
  return new Blob([view], { type: "audio/wav" });
}

async function recordingToWav(recording: Blob): Promise<Blob> {
  const AudioContextCtor = getAudioContext();
  if (!AudioContextCtor) throw new Error("Audio conversion is unavailable in this browser.");
  const context = new AudioContextCtor();
  try {
    const decoded = await context.decodeAudioData(await recording.arrayBuffer());
    const mono = new Float32Array(decoded.length);
    for (let channel = 0; channel < decoded.numberOfChannels; channel += 1) {
      const data = decoded.getChannelData(channel);
      for (let i = 0; i < data.length; i += 1) mono[i] += data[i] / decoded.numberOfChannels;
    }
    return encodeMonoWav(mono, decoded.sampleRate);
  } finally {
    await context.close().catch(() => undefined);
  }
}

// Read a recorded audio Blob as a bare base64 string (no data: prefix).
function blobToBase64(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    const r = new FileReader();
    r.onloadend = () => resolve(String(r.result).split(",").pop() || "");
    r.onerror = reject;
    r.readAsDataURL(blob);
  });
}

export function AssistantClient() {
  const params = useSearchParams();
  const lang = useAppStore((s) => s.lang);
  const t = useT();
  const [turns, setTurns] = useState<Turn[]>([]);
  const [input, setInput] = useState("");
  const [listening, setListening] = useState(false);
  const [voiceSupported, setVoiceSupported] = useState(false);
  const [voiceBusy, setVoiceBusy] = useState(false);
  const [voiceMsg, setVoiceMsg] = useState<string | null>(null);
  const [scanning, setScanning] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null);
  const scrollRef = useRef<HTMLDivElement>(null);
  const recRef = useRef<SpeechRecognitionLike | null>(null);
  const mediaRecorderRef = useRef<MediaRecorder | null>(null);
  const mediaStreamRef = useRef<MediaStream | null>(null);
  const recordTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const turnsRef = useRef<Turn[]>([]);
  turnsRef.current = turns;
  const idRef = useRef(0);

  useEffect(() => {
    const canRecord = typeof navigator.mediaDevices?.getUserMedia === "function"
      && typeof MediaRecorder !== "undefined"
      && !!getAudioContext();
    setVoiceSupported(canRecord || !!getSpeechRecognition());
    return () => {
      if (recordTimerRef.current) clearTimeout(recordTimerRef.current);
      mediaRecorderRef.current?.stop();
      mediaStreamRef.current?.getTracks().forEach((track) => track.stop());
      recRef.current?.stop();
    };
  }, []);

  const ask = useCallback(async (q: string, viaVoice = false) => {
    if (!q.trim()) return;
    setInput("");
    // Conversation memory: send previous user turns so follow-ups
    // ("what about vehicle theft?") resolve against earlier context.
    const history = turnsRef.current.map((t) => t.q).slice(-8);
    // Stable per-turn id so a response always updates its own turn, even if the
    // user fires another question while this one is still loading.
    void history;
    void viaVoice;
    const id = ++idRef.current;
    setTurns((t) => [...t, { id, q, loading: true }]);
    if (!aiConfigured()) {
      setTurns((t) => t.map((x) => (x.id === id ? { id, q, insight: textInsight(
        "The AI assistant isn't connected in this build. Set NEXT_PUBLIC_AI_FN_URL to your Catalyst Function endpoint to enable live answers. The rest of NETRA — cases, criminals, network, maps, analytics — works from the loaded records.",
        "demo-engine",
      ) } : x)));
      return;
    }
    try {
      // RAG first: retrieve the relevant case documents and answer grounded in
      // them. Fall back to a plain LLM answer if the knowledge base isn't set up.
      const rag = await askRag(q);
      let insight: AiInsight;
      if (rag) {
        insight = ragInsight(rag.answer, rag.sources);
      } else {
        const text = await askAssistant(q, { system: NETRA_SYSTEM });
        insight = text
          ? textInsight(text, "llm")
          : textInsight("The AI backend didn't return an answer. Check the Catalyst Function, the QuickML token, and that case documents are uploaded to the RAG knowledge base, then try again.", "demo-engine");
      }
      setTurns((t) => t.map((x) => (x.id === id ? { id, q, insight } : x)));
    } catch {
      setTurns((t) => t.map((x) => (x.id === id ? { id, q, insight: undefined } : x)));
    }
  }, []);

  const prepareVoiceTranscript = useCallback(async (transcript: string) => {
    setVoiceMsg("Analyzing command with Catalyst Zia...");
    const analyzed = await analyzeVoiceCommand(transcript);
    const command = analyzed?.text || transcript;
    setVoiceMsg(null);
    setInput(command);
  }, []);

  // Speech recognition creates the transcript; Catalyst Zia Text Analytics
  // processes it before the officer reviews and submits the command.
  const startWebSpeech = useCallback(() => {
    const SR = getSpeechRecognition();
    if (!SR) { setListening(false); return; }
    const rec = new SR();
    rec.lang = lang === "kn" ? "kn-IN" : "en-IN";
    rec.interimResults = true;
    rec.continuous = false;
    rec.onresult = (e) => {
      const results = Array.from(e.results as ArrayLike<ArrayLike<{ transcript: string }> & { isFinal: boolean }>);
      const transcript = results.map((r) => r[0]?.transcript ?? "").join(" ").trim();
      // Drop the transcript into the composer so the officer can review or edit
      // before hitting send — do NOT auto-submit.
      setInput(transcript);
      const last = results[results.length - 1];
      if (last?.isFinal && transcript) {
        setListening(false);
        void prepareVoiceTranscript(transcript);
      }
    };
    rec.onend = () => setListening(false);
    rec.onerror = (e) => { setListening(false); setVoiceMsg(speechErr(e?.error)); };
    recRef.current = rec;
    setListening(true);
    setVoiceMsg(null);
    rec.start();
  }, [lang, prepareVoiceTranscript]);

  const startCloudRecording = useCallback(async () => {
    if (typeof navigator.mediaDevices?.getUserMedia !== "function" || typeof MediaRecorder === "undefined" || !getAudioContext()) {
      startWebSpeech();
      return;
    }
    try {
      setVoiceMsg("Allow microphone access, then speak your command.");
      const stream = await navigator.mediaDevices.getUserMedia({
        audio: { channelCount: 1, echoCancellation: true, noiseSuppression: true },
      });
      mediaStreamRef.current = stream;
      const preferred = ["audio/webm;codecs=opus", "audio/mp4", "audio/ogg;codecs=opus"]
        .find((type) => MediaRecorder.isTypeSupported(type));
      const recorder = preferred ? new MediaRecorder(stream, { mimeType: preferred }) : new MediaRecorder(stream);
      const chunks: Blob[] = [];
      recorder.ondataavailable = (event) => {
        if (event.data.size) chunks.push(event.data);
      };
      recorder.onerror = () => {
        setListening(false);
        setVoiceBusy(false);
        setVoiceMsg("Microphone recording failed. Check browser microphone permission and try again.");
      };
      recorder.onstop = async () => {
        if (recordTimerRef.current) clearTimeout(recordTimerRef.current);
        recordTimerRef.current = null;
        mediaStreamRef.current?.getTracks().forEach((track) => track.stop());
        mediaStreamRef.current = null;
        setListening(false);
        if (!chunks.length) {
          setVoiceMsg("No audio was captured. Check the selected microphone and try again.");
          return;
        }
        setVoiceBusy(true);
        setVoiceMsg("Transcribing with Catalyst Zia...");
        try {
          const recording = new Blob(chunks, { type: recorder.mimeType || preferred || "audio/webm" });
          const wav = await recordingToWav(recording);
          const audio = await blobToBase64(wav);
          const result = await transcribeAudio(audio, lang === "kn" ? "kn" : "en");
          if (!result?.text) {
            setVoiceMsg("Catalyst could not recognise speech. Speak clearly and try again.");
            return;
          }
          await prepareVoiceTranscript(result.text);
        } catch {
          setVoiceMsg("Voice processing failed. Check the Catalyst Function and try again.");
        } finally {
          setVoiceBusy(false);
        }
      };
      mediaRecorderRef.current = recorder;
      recorder.start(250);
      setListening(true);
      setVoiceMsg(null);
      recordTimerRef.current = setTimeout(() => {
        if (recorder.state === "recording") recorder.stop();
      }, 12000);
    } catch (error) {
      const name = error instanceof DOMException ? error.name : "";
      setListening(false);
      setVoiceMsg(
        name === "NotAllowedError"
          ? "Microphone permission denied. Allow microphone access for this site, then try again."
          : "No microphone is available. Check the browser input device and try again."
      );
    }
  }, [lang, prepareVoiceTranscript, startWebSpeech]);

  const toggleMic = useCallback(() => {
    if (voiceBusy) return;
    if (listening) {
      if (mediaRecorderRef.current?.state === "recording") {
        mediaRecorderRef.current.stop();
        return;
      }
      recRef.current?.stop();
      return;
    }
    if (!voiceSupported) {
      setVoiceMsg("Voice input needs microphone access in a current Chrome, Edge, Firefox, or Safari browser.");
      return;
    }
    void startCloudRecording();
  }, [listening, startCloudRecording, voiceBusy, voiceSupported]);

  // Scan an FIR document — Catalyst Zia OCR via the Function. Extracted text
  // drops into the ask box (and the Function stores the scan + result).
  const onScan = useCallback(async (file: File | null) => {
    if (!file) return;
    setScanning(true);
    try {
      const b64 = await blobToBase64(file);
      const res = await extractText(b64, lang === "kn" ? "kan" : "eng", file.name);
      if (res?.text) setInput((prev) => (prev ? `${prev}\n${res.text}` : res.text));
      else setInput("Could not read text from that document. Try a clearer scan.");
    } catch {
      setInput("Document scan failed — check the Catalyst Function / Zia OCR.");
    } finally {
      setScanning(false);
      if (fileRef.current) fileRef.current.value = "";
    }
  }, [lang]);

  // Conversation → PDF (print pipeline; audit-logged).
  const exportPdf = useCallback(() => {
    window.print();
  }, []);

  // Auto-run a query passed via ?q= (from global search)
  useEffect(() => {
    const q = params.get("q");
    if (q) ask(q);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" });
  }, [turns]);

  const empty = turns.length === 0;

  return (
    <div className="flex h-[calc(100vh-8.5rem)] flex-col print:block print:h-auto">
      {/* Header */}
      <div className="mb-5 flex items-center gap-3">
        <div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-border/60 bg-accent/10 shadow-glow print:hidden">
          <Sparkles className="h-5 w-5 text-accent" />
        </div>
        <div className="min-w-0">
          <h1 className="font-display text-2xl font-bold tracking-tight">{t("assistant.title")}</h1>
          <p className="mt-0.5 text-sm text-muted print:hidden">{t("assistant.subtitle")}</p>
          <p className="hidden text-sm text-muted print:block" suppressHydrationWarning>
            NETRA — Conversation transcript · Karnataka State Police (demo)
          </p>
        </div>
        <div className="ml-auto flex shrink-0 items-center gap-2 print:hidden">
          <Badge tone="accent"><Cpu className="h-3 w-3" /> On-device routing</Badge>
          {!empty && (
            <button onClick={exportPdf} className="btn-ghost" title="Export conversation as PDF">
              <FileDown className="h-4 w-4" /> {t("assistant.export")}
            </button>
          )}
        </div>
      </div>

      {/* Conversation */}
      <div ref={scrollRef} className="flex-1 space-y-6 overflow-y-auto pr-1 print:overflow-visible">
        {empty && (
          <div className="card panel-pad animate-fade-in space-y-5">
            <div>
              <div className="flex items-center gap-1.5 stat-label text-accent">
                <Lightbulb className="h-3.5 w-3.5" /> {t("assistant.try")}
              </div>
              <div className="mt-3 flex flex-wrap gap-2">
                {EXAMPLES.map((e) => (
                  <button key={e} onClick={() => ask(e)} className="chip max-w-full text-left transition-colors hover:border-accent/50 hover:text-fg">
                    {e}
                  </button>
                ))}
              </div>
            </div>
            <div className="flex items-start gap-2.5 rounded-lg border border-border/70 bg-elevated/60 p-3.5 text-xs leading-relaxed text-muted">
              <ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-accent" />
              <span>
                NETRA never sends raw records to a black box. Queries run through intent detection → permission checks →
                validated SQL → evidence verification → audit log. The officer stays in command.
              </span>
            </div>
          </div>
        )}

        {turns.map((t) => (
          <div key={t.id} className="space-y-3">
            {/* user */}
            <div className="flex items-start justify-end gap-2">
              <div className="max-w-[80%] rounded-2xl rounded-tr-sm bg-accent/10 px-4 py-2.5 text-sm text-fg">{t.q}</div>
              <div className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-elevated">
                <User className="h-3.5 w-3.5 text-muted" />
              </div>
            </div>
            {/* assistant */}
            <div className="flex items-start gap-2">
              <div className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-accent/10">
                <Sparkles className="h-3.5 w-3.5 text-accent" />
              </div>
              <div className="min-w-0 flex-1">
                {t.loading ? (
                  <div className="card panel-pad animate-fade-in space-y-3.5">
                    <div className="flex items-center gap-2 text-sm text-muted">
                      <Loader2 className="h-4 w-4 animate-spin text-accent" /> Reasoning over crime records…
                    </div>
                    <div className="space-y-2" aria-hidden>
                      <div className="skeleton h-3 w-full" />
                      <div className="skeleton h-3 w-11/12" />
                      <div className="skeleton h-3 w-3/4" />
                    </div>
                  </div>
                ) : t.insight ? (
                  <InsightCard insight={t.insight} onAlt={ask} lang={lang} />
                ) : (
                  <div className="text-sm text-danger">Something went wrong. Please try again.</div>
                )}
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Option A — one-click investigative tasks (all answered by the local engine) */}
      <div className="mt-3 flex flex-wrap items-center gap-1.5 border-t border-border/60 pt-3 print:hidden">
        <span className="flex items-center gap-1 text-[11px] text-muted"><Route className="h-3 w-3" /> Quick tasks:</span>
        {TASKS.map((task) => (
          <button
            key={task.label}
            onClick={() => ask(task.q)}
            className="chip text-[11px] hover:border-accent/50 hover:text-fg"
            title={task.q}
          >
            <task.icon className="h-3 w-3 text-accent" /> {task.label}
          </button>
        ))}
      </div>

      {(listening || voiceBusy || voiceMsg) && (
        <p className={cn("mb-1 text-xs", voiceMsg ? "text-warning" : "text-accent")}>
          {voiceMsg || "🎙 Listening… speak now, then tap the mic again to stop."}
        </p>
      )}

      {/* Composer */}
      <form
        onSubmit={(e) => {
          e.preventDefault();
          ask(input);
        }}
        className="mt-3 flex items-center gap-2 print:hidden"
      >
        <div className="relative flex-1">
          <input
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder={listening ? "Listening… speak now" : t("assistant.placeholder")}
            className={cn("input h-12 pr-24", listening && "border-accent/60")}
          />
          <span className="kbd pointer-events-none absolute right-3 top-1/2 -translate-y-1/2">
            <CornerDownLeft className="inline h-3 w-3" /> enter
          </span>
        </div>
        <input
          ref={fileRef}
          type="file"
          accept="image/*"
          className="hidden"
          onChange={(e) => onScan(e.target.files?.[0] ?? null)}
        />
        <button
          type="button"
          onClick={() => fileRef.current?.click()}
          disabled={scanning}
          className={cn("btn-ghost h-12 w-12 shrink-0 justify-center px-0", scanning && "text-accent")}
          title="Scan an FIR document (Zia OCR)"
          aria-label="Scan document"
        >
          {scanning ? <Loader2 className="h-4 w-4 animate-spin" /> : <ScanText className="h-4 w-4" />}
        </button>
        <button
          type="button"
          onClick={toggleMic}
          className={cn(
            "btn-ghost h-12 w-12 shrink-0 justify-center px-0",
            listening && "border-accent/60 text-accent",
            voiceBusy && "border-accent/40 text-accent"
          )}
          title={
            listening
              ? "Stop listening"
              : `Voice command (${lang === "kn" ? "ಕನ್ನಡ" : "English"}) via Catalyst Zia speech and NLP`
          }
          aria-label="Voice input"
          aria-pressed={listening}
        >
          {voiceBusy
            ? <Loader2 className="h-4 w-4 animate-spin" />
            : listening
            ? <MicOff className="h-4 w-4 animate-pulse" />
            : <Mic className="h-4 w-4" />}
        </button>
        <button className="btn-accent h-12 px-5" disabled={!input.trim()}>
          <Send className="h-4 w-4" />
        </button>
      </form>
    </div>
  );
}

function InsightCard({ insight, onAlt, lang }: { insight: AiInsight; onAlt: (q: string) => void; lang: string }) {
  const [showSql, setShowSql] = useState(false);
  const [showData, setShowData] = useState(false);
  const [speaking, setSpeaking] = useState(false);
  const [kannada, setKannada] = useState<string | null>(null);
  const [translating, setTranslating] = useState(false);
  const audioRef = useRef<HTMLAudioElement | null>(null);
  const e = insight.explain;
  const pct = Math.round(e.confidence * 100);
  const confTone = pct >= 80 ? "text-success" : pct >= 60 ? "text-warning" : "text-muted";
  const spoken = kannada ?? insight.answer;

  // Read aloud via Catalyst Zia TTS; fall back to the browser voice if the
  // Function/Zia is unavailable so the button always does something.
  const speak = useCallback(async () => {
    if (speaking) {
      audioRef.current?.pause();
      if (typeof window !== "undefined" && "speechSynthesis" in window) window.speechSynthesis.cancel();
      setSpeaking(false);
      return;
    }
    setSpeaking(true);
    const b64 = await synthesizeSpeech(spoken, kannada ? "kn-IN" : lang === "kn" ? "kn-IN" : "en-IN");
    if (b64) {
      const audio = new Audio(b64.startsWith("data:") ? b64 : `data:audio/wav;base64,${b64}`);
      audioRef.current = audio;
      audio.onended = () => setSpeaking(false);
      audio.onerror = () => setSpeaking(false);
      audio.play().catch(() => setSpeaking(false));
      return;
    }
    if (typeof window !== "undefined" && "speechSynthesis" in window) {
      const u = new SpeechSynthesisUtterance(spoken);
      u.lang = kannada ? "kn-IN" : lang === "kn" ? "kn-IN" : "en-IN";
      u.onend = () => setSpeaking(false);
      u.onerror = () => setSpeaking(false);
      window.speechSynthesis.cancel();
      window.speechSynthesis.speak(u);
      return;
    }
    setSpeaking(false);
  }, [spoken, kannada, lang, speaking]);

  // Translate the answer to Kannada via Catalyst Zia.
  const translate = useCallback(async () => {
    if (kannada) { setKannada(null); return; }
    setTranslating(true);
    const kn = await translateText(insight.answer, "kn", "en");
    setKannada(kn);
    setTranslating(false);
  }, [insight.answer, kannada]);

  return (
    <div className="card panel-pad animate-fade-in space-y-4">
      <div className="flex items-start gap-2">
        <p className="flex-1 text-[15px] leading-relaxed text-fg">
          {/* Manual per-answer translate takes precedence; otherwise the global
              EN|ಕನ್ನಡ toggle drives translate-on-display via <Translated>. */}
          {kannada ?? <Translated text={insight.answer} />}
        </p>
        <button
          onClick={translate}
          disabled={translating}
          className={cn("shrink-0 rounded-md px-2 py-1.5 text-xs font-medium text-muted transition-colors hover:bg-elevated hover:text-fg disabled:opacity-50 print:hidden", kannada && "text-accent")}
          title={kannada ? "Show English" : "Translate to Kannada (ಕನ್ನಡ)"}
          aria-label="Translate to Kannada"
        >
          {translating ? <Loader2 className="h-4 w-4 animate-spin" /> : kannada ? "EN" : "ಕನ್ನಡ"}
        </button>
        <button
          onClick={speak}
          className={cn("shrink-0 rounded-md p-1.5 text-muted transition-colors hover:bg-elevated hover:text-fg print:hidden", speaking && "text-accent")}
          title={speaking ? "Stop reading" : "Read answer aloud"}
          aria-label="Read answer aloud"
        >
          <Volume2 className={cn("h-4 w-4", speaking && "animate-pulse")} />
        </button>
      </div>

      {/* meta */}
      <div className="flex flex-wrap items-center gap-2 text-xs">
        <span className="chip">
          <Database className="h-3 w-3 text-accent" /> {SOURCE_LABEL[e.source] || e.source}
        </span>
        {/* Option C — smart routing: which local engine handled this query */}
        <span className="chip font-mono text-accent" title="Query was automatically routed to the best local engine — no external AI is ever used">
          <Route className="h-3 w-3" /> routed to {routeLabel(e.ai_model)}
        </span>
        <span className={cn("chip font-mono", confTone)}>confidence {pct}%</span>
        <span className="chip font-mono">{e.records_used} records</span>
        <span className="chip font-mono">{e.processing_ms}ms</span>
        <span className="chip font-mono text-muted"><Cpu className="h-3 w-3" /> on-device</span>
      </div>

      {/* conversation-memory context */}
      {e.context_used && e.context_used.length > 0 && (
        <div className="flex flex-wrap items-center gap-1.5 text-xs">
          <span className="flex items-center gap-1 text-muted"><History className="h-3 w-3" /> Context:</span>
          {e.context_used.map((c, i) => (
            <span key={i} className="chip text-[10px] text-info">{c}</span>
          ))}
        </div>
      )}

      {/* chart */}
      {insight.chart && insight.rows && insight.rows.length > 1 && (
        <div className="rounded-lg border border-border bg-elevated p-3">
          {insight.chart.kind === "line" ? (
            <TrendLine data={insight.rows} x={insight.chart.x} y={insight.chart.y} height={200} />
          ) : (
            <BarSeries data={insight.rows.slice(0, 12)} x={insight.chart.x} y={insight.chart.y} height={220} />
          )}
        </div>
      )}

      {/* explainability */}
      <div className="rounded-lg border border-border bg-elevated p-3 text-sm">
        <div className="mb-1 flex items-center gap-1.5 text-xs font-semibold text-accent">
          <ShieldCheck className="h-3.5 w-3.5" /> Why this answer
        </div>
        <p className="text-muted">{e.reasoning}</p>
        {e.evidence.length > 0 && (
          <div className="mt-2">
            <span className="stat-label">{e.source === "rag" ? "Source documents" : "Records used"}</span>
            <div className="mt-1 flex flex-wrap gap-1.5">
              {e.evidence.map((ev, i) => (
                <span key={i} className="chip font-mono text-[10px]">{ev}</span>
              ))}
            </div>
          </div>
        )}
        <div className="mt-2 text-[11px] text-muted">Audit ID · <span className="font-mono">{e.audit_id}</span></div>
      </div>

      {/* data table */}
      {insight.rows && insight.rows.length > 0 && (
        <div className="print:hidden">
          <button onClick={() => setShowData((s) => !s)} className="flex items-center gap-1 text-xs font-medium text-subtle hover:text-fg">
            <ChevronDown className={cn("h-3.5 w-3.5 transition-transform", showData && "rotate-180")} />
            {showData ? "Hide" : "Show"} data ({insight.rows.length} rows)
          </button>
          {showData && (
            <div className="mt-2 max-h-72 overflow-auto rounded-lg border border-border">
              <table className="w-full text-left text-xs">
                <thead className="sticky top-0 bg-elevated">
                  <tr>
                    {insight.columns?.map((c) => (
                      <th key={c} className="whitespace-nowrap px-3 py-2 font-medium text-muted">{c}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {insight.rows.slice(0, 50).map((r, i) => (
                    <tr key={i} className="border-t border-border/50">
                      {insight.columns?.map((c) => (
                        <td key={c} className="whitespace-nowrap px-3 py-1.5 font-mono text-subtle">{String(r[c] ?? "")}</td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      )}

      {/* SQL */}
      {insight.sql && (
        <div className="print:hidden">
          <button onClick={() => setShowSql((s) => !s)} className="flex items-center gap-1 text-xs font-medium text-subtle hover:text-fg">
            <ChevronDown className={cn("h-3.5 w-3.5 transition-transform", showSql && "rotate-180")} />
            {showSql ? "Hide" : "Show"} generated SQL
          </button>
          {showSql && (
            <pre className="mt-2 overflow-x-auto rounded-lg border border-border bg-bg p-3 font-mono text-[11px] leading-relaxed text-subtle">
              {insight.sql}
            </pre>
          )}
        </div>
      )}

      {/* alternatives */}
      {e.alternatives.length > 0 && (
        <div className="print:hidden">
          <span className="stat-label">Follow-up</span>
          <div className="mt-1.5 flex flex-wrap gap-2">
            {e.alternatives.map((a, i) => (
              <button key={i} onClick={() => onAlt(a)} className="chip hover:border-accent/50 hover:text-fg">
                {a}
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
