"use client";
import { useState, useRef, useEffect, useCallback, useMemo, Fragment } from "react";
import { useSearchParams } from "next/navigation";
import {
  Search, ArrowRight, Database, ChevronDown, ShieldCheck, CornerDownLeft, Loader2,
  Mic, MicOff, Volume2, FileDown, History, Cpu, Route, ScanText, ScanSearch,
  UserSearch, Network as NetworkIcon, Flame, GitCompare, Users, FileText,
  ListChecks, FolderSearch, Hash, Terminal, AlertTriangle, BadgeCheck, ChevronRight, X,
} from "lucide-react";
import type { AiInsight } from "@/lib/types";
import { TrendLine, BarSeries } from "@/components/charts";
import { cn } from "@/lib/utils";
import { useAppStore } from "@/store/useAppStore";
import { useT } from "@/lib/i18n-client";
import { askAssistant, askRag, aiConfigured, translateText, synthesizeSpeech, analyzeVoiceCommand, transcribeAudio, extractText, exportConversationPdf, searchCloudRecords, type RagSource } from "@/lib/ai-client";
import { Translated } from "@/components/Translated";
import { parseBlocks, keyFindings, extractFirs, naturalizeForSpeech, type AnswerBlock } from "@/lib/answer-format";
import type { AiResponseMeta, ConversationMessage } from "@/lib/ai-client";

const HISTORY_KEY = "netra_assistant_history_v1";
const STALE_BACKEND_FAILURE = /AI backend didn't return an answer|AI assistant isn't connected in this build/i;

const NETRA_SYSTEM =
  "You are NETRA, an AI crime-investigation assistant for the Karnataka State Police. " +
  "Answer the officer's question clearly and concisely. If the question needs specific case " +
  "records you do not have, say so and suggest where in NETRA to look (cases, criminals, network, maps).";

/** Build an AiInsight shell around a plain-text answer from the Catalyst Function. */
function textInsight(answer: string, source: AiInsight["explain"]["source"], meta: AiResponseMeta = {}): AiInsight {
  const cloudScaleFallback = /Cloud Scale Retrieval/i.test(meta.model || "");
  return {
    answer,
    explain: {
      confidence: cloudScaleFallback ? 0.72 : source === "llm" ? 0.82 : 0.4,
      reasoning: cloudScaleFallback
        ? "QuickML was unavailable, so NETRA returned a bounded, auditable answer from Catalyst Cloud Scale records."
        : source === "llm" ? "Generated by Zoho Catalyst QuickML." : "AI backend not connected in this build.",
      records_used: 0,
      evidence: [],
      alternatives: [],
      source: cloudScaleFallback ? "lookup" : source,
      audit_id: meta.audit_id || `A-${Date.now().toString(36).toUpperCase()}`,
      processing_ms: meta.processing_ms || 0,
      ai_model: meta.model || (source === "llm" ? "VL-Qwen3.6-35B-A3B" : "none"),
    },
  };
}

/** Build an AiInsight from a RAG answer + the case documents it was grounded on. */
function ragInsight(answer: string, sources: RagSource[], meta: AiResponseMeta = {}): AiInsight {
  const cloudScaleFallback = /Cloud Scale Retrieval/i.test(meta.model || "");
  const evidence = sources
    .map((s) => (s.title || s.snippet || "").toString().slice(0, 80))
    .filter(Boolean)
    .slice(0, 8);
  return {
    answer,
    // Keep the rich source structure (title/snippet/score) for the Sources panel.
    sources: sources.slice(0, 8).map((s) => ({
      title: (s.title || "").toString(),
      snippet: (s.snippet || "").toString(),
      score: typeof s.score === "number" ? s.score : null,
    })),
    explain: {
      confidence: cloudScaleFallback ? 0.72 : 0.85,
      reasoning: cloudScaleFallback
        ? "QuickML was unavailable, so NETRA answered from the cited Catalyst Cloud Scale records."
        : sources.length
        ? `Grounded in ${sources.length} case document${sources.length === 1 ? "" : "s"} retrieved from the knowledge base by Zoho Catalyst QuickML RAG.`
        : "Answered by Zoho Catalyst QuickML RAG (no source passages returned).",
      records_used: sources.length,
      evidence,
      alternatives: [],
      source: cloudScaleFallback ? "lookup" : "rag",
      audit_id: meta.audit_id || `A-${Date.now().toString(36).toUpperCase()}`,
      processing_ms: meta.processing_ms || 0,
      ai_model: meta.model || "QuickML RAG",
    },
  };
}

function value(row: Record<string, unknown>, ...keys: string[]): string {
  for (const key of keys) {
    const raw = row[key];
    if (raw != null && String(raw).trim()) return String(raw);
  }
  return "";
}

function searchInsight(query: string, hits: Array<{ table: string; row: Record<string, unknown> }>, warning?: string | null, meta: AiResponseMeta = {}): AiInsight {
  const lines = hits.slice(0, 6).map((hit, index) => {
    const row = hit.row;
    const primary = value(row, "fir_number", "case_number", "name", "full_name", "vehicle_number", "record_id", "ROWID") || "record";
    const detail = [
      value(row, "crime_type", "offence_type", "status"),
      value(row, "district", "station_name", "location"),
      value(row, "description", "summary", "notes").slice(0, 110),
    ].filter(Boolean).join(" · ");
    return `${index + 1}. ${hit.table}: ${primary}${detail ? ` — ${detail}` : ""}`;
  });
  return {
    answer: `Cloud Scale search is live for "${query}". I found ${hits.length} relevant record${hits.length === 1 ? "" : "s"}:\n\n${lines.join("\n")}${warning ? `\n\nNote: ${warning}` : ""}`,
    explain: {
      confidence: 0.72,
      reasoning: "QuickML RAG/chat did not return a usable answer, so NETRA answered from bounded Catalyst Cloud Scale search results.",
      records_used: hits.length,
      evidence: hits.slice(0, 8).map((hit) => `${hit.table} · ${value(hit.row, "fir_number", "case_number", "name", "ROWID") || "record"}`),
      alternatives: [],
      source: "lookup",
      audit_id: meta.audit_id || `A-${Date.now().toString(36).toUpperCase()}`,
      processing_ms: meta.processing_ms || 0,
      ai_model: meta.model || "Catalyst Cloud Scale Search",
    },
  };
}

interface Turn {
  id: number;
  q: string;
  ts: number;
  insight?: AiInsight;
  loading?: boolean;
}

// Queries that hit the QuickML RAG knowledge base (the uploaded case dossiers).
const EXAMPLES: { icon: typeof FolderSearch; q: string; hint: string }[] = [
  { icon: FolderSearch, q: "What crimes are recorded in the case files?", hint: "Case-file overview" },
  { icon: UserSearch, q: "Summarise the burglary cases and the accused", hint: "Accused & modus operandi" },
  { icon: NetworkIcon, q: "Tell me about the cybercrime OTP fraud case", hint: "Cyber / financial fraud" },
  { icon: GitCompare, q: "Which cases involve vehicle theft?", hint: "Cross-case pattern" },
  { icon: ListChecks, q: "What evidence was collected in these cases?", hint: "Evidence inventory" },
];

const SOURCE_LABEL: Record<string, string> = {
  "template-sql": "Verified SQL",
  llm: "Catalyst QuickML",
  rag: "QuickML · RAG",
  cache: "Cache",
  "demo-engine": "Keyword search",
  semantic: "Semantic search",
  lookup: "Database dossier",
};

// One-click prompts, each grounded in the RAG knowledge base (case dossiers).
const TASKS: { icon: typeof UserSearch; label: string; q: string }[] = [
  { icon: Flame, label: "All crimes", q: "What crimes are recorded in the case files?" },
  { icon: UserSearch, label: "Burglary", q: "Summarise the burglary cases and the accused" },
  { icon: NetworkIcon, label: "Cybercrime", q: "Tell me about the cybercrime OTP fraud case" },
  { icon: GitCompare, label: "Vehicle theft", q: "Which cases involve vehicle theft?" },
  { icon: Users, label: "Evidence", q: "What evidence was collected in these cases?" },
];

// Friendly label for the engine that handled a query (option C — smart routing).
const ROUTE_LABEL: Record<string, string> = {
  "rule-engine": "rule-engine (local · instant)",
  "tfidf-embeddings": "semantic index (local)",
  "db-lookup": "database lookup (local)",
  fallback: "keyword fallback (local)",
};
// Headings the model tends to echo that duplicate our own section labels — we
// drop these from the summary so the dossier structure isn't repeated.
const SECTION_ECHO = /^(investigation summary|summary|overview|key findings?|findings|highlights|related (fir|firs|case|cases)|firs|cases|evidence|sources?|source documents?|records? used|verification|answer|result)\s*:?\s*$/i;

function routeLabel(model: string): string {
  if (ROUTE_LABEL[model]) return ROUTE_LABEL[model];
  if (/rag/i.test(model)) return "Catalyst QuickML · RAG";
  return `Catalyst QuickML · ${model}`;
}
function engineScope(source: AiInsight["explain"]["source"]): string {
  if (source === "rag" || source === "llm") return "Catalyst";
  if (source === "lookup") return "Cloud Scale";
  return "local";
}

/* Minimal typings for the Web Speech API (not in TS dom lib everywhere). */
type SpeechRecognitionLike = {
  lang: string;
  interimResults: boolean;
  continuous: boolean;
  onresult: ((e: { results: ArrayLike<ArrayLike<{ transcript: string }> & { isFinal: boolean }> }) => void) | null;
  onend: (() => void) | null;
  onerror: ((e?: { error?: string }) => void) | null;
  start: () => void;
  stop: () => void;
};

const SPEECH_ERR: Record<string, string> = {
  "not-allowed": "Microphone permission denied — allow mic access in the browser.",
  "service-not-allowed": "Microphone permission denied — allow mic access in the browser.",
  "no-speech": "No speech detected — try again and speak clearly.",
  "audio-capture": "No microphone found.",
  "language-not-supported": "This browser can't recognise the selected language. Switch to English or use Chrome.",
  "network": "Network error reaching the speech service.",
};
function speechErr(code?: string): string {
  return SPEECH_ERR[code || ""] || "Voice input failed — try Chrome, or deploy the Catalyst Zia path.";
}

function getSpeechRecognition(): (new () => SpeechRecognitionLike) | null {
  if (typeof window === "undefined") return null;
  const w = window as unknown as Record<string, unknown>;
  return (w.SpeechRecognition || w.webkitSpeechRecognition) as (new () => SpeechRecognitionLike) | null;
}

function getAudioContext(): typeof AudioContext | null {
  if (typeof window === "undefined") return null;
  const w = window as typeof window & { webkitAudioContext?: typeof AudioContext };
  return window.AudioContext || w.webkitAudioContext || null;
}

function encodeMonoWav(samples: Float32Array, sampleRate: number): Blob {
  const buffer = new ArrayBuffer(44 + samples.length * 2);
  const view = new DataView(buffer);
  const write = (offset: number, value: string) => {
    for (let i = 0; i < value.length; i += 1) view.setUint8(offset + i, value.charCodeAt(i));
  };
  write(0, "RIFF");
  view.setUint32(4, 36 + samples.length * 2, true);
  write(8, "WAVE");
  write(12, "fmt ");
  view.setUint32(16, 16, true);
  view.setUint16(20, 1, true);
  view.setUint16(22, 1, true);
  view.setUint32(24, sampleRate, true);
  view.setUint32(28, sampleRate * 2, true);
  view.setUint16(32, 2, true);
  view.setUint16(34, 16, true);
  write(36, "data");
  view.setUint32(40, samples.length * 2, true);
  let offset = 44;
  for (let i = 0; i < samples.length; i += 1, offset += 2) {
    const sample = Math.max(-1, Math.min(1, samples[i]));
    view.setInt16(offset, sample < 0 ? sample * 0x8000 : sample * 0x7fff, true);
  }
  return new Blob([view], { type: "audio/wav" });
}

async function recordingToWav(recording: Blob): Promise<Blob> {
  const AudioContextCtor = getAudioContext();
  if (!AudioContextCtor) throw new Error("Audio conversion is unavailable in this browser.");
  const context = new AudioContextCtor();
  try {
    const decoded = await context.decodeAudioData(await recording.arrayBuffer());
    const mono = new Float32Array(decoded.length);
    for (let channel = 0; channel < decoded.numberOfChannels; channel += 1) {
      const data = decoded.getChannelData(channel);
      for (let i = 0; i < data.length; i += 1) mono[i] += data[i] / decoded.numberOfChannels;
    }
    return encodeMonoWav(mono, decoded.sampleRate);
  } finally {
    await context.close().catch(() => undefined);
  }
}

// Read a recorded audio Blob as a bare base64 string (no data: prefix).
function blobToBase64(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    const r = new FileReader();
    r.onloadend = () => resolve(String(r.result).split(",").pop() || "");
    r.onerror = reject;
    r.readAsDataURL(blob);
  });
}

function fmtTime(ts: number): string {
  try {
    return new Date(ts).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
  } catch {
    return "";
  }
}

export function AssistantClient() {
  const params = useSearchParams();
  const lang = useAppStore((s) => s.lang);
  const t = useT();
  const [turns, setTurns] = useState<Turn[]>([]);
  const [input, setInput] = useState("");
  const [listening, setListening] = useState(false);
  const [voiceSupported, setVoiceSupported] = useState(false);
  const [voiceBusy, setVoiceBusy] = useState(false);
  const [voiceMsg, setVoiceMsg] = useState<string | null>(null);
  const [scanning, setScanning] = useState(false);
  const [pdfBusy, setPdfBusy] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const resultsRef = useRef<HTMLDivElement>(null);
  const recRef = useRef<SpeechRecognitionLike | null>(null);
  const mediaRecorderRef = useRef<MediaRecorder | null>(null);
  const mediaStreamRef = useRef<MediaStream | null>(null);
  const recordTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const turnsRef = useRef<Turn[]>([]);
  turnsRef.current = turns;
  const idRef = useRef(0);

  useEffect(() => {
    const canRecord = typeof navigator.mediaDevices?.getUserMedia === "function"
      && typeof MediaRecorder !== "undefined"
      && !!getAudioContext();
    setVoiceSupported(canRecord || !!getSpeechRecognition());
    return () => {
      if (recordTimerRef.current) clearTimeout(recordTimerRef.current);
      mediaRecorderRef.current?.stop();
      mediaStreamRef.current?.getTracks().forEach((track) => track.stop());
      recRef.current?.stop();
    };
  }, []);

  useEffect(() => {
    try {
      const saved = JSON.parse(localStorage.getItem(HISTORY_KEY) || "[]") as Turn[];
      const restored = Array.isArray(saved)
        ? saved.filter((turn) => turn && typeof turn.q === "string" && turn.insight).slice(-20)
          .filter((turn) => !STALE_BACKEND_FAILURE.test(turn.insight?.answer || ""))
        : [];
      setTurns(restored);
      idRef.current = restored.reduce((max, turn) => Math.max(max, Number(turn.id) || 0), 0);
    } catch {
      localStorage.removeItem(HISTORY_KEY);
    }
  }, []);

  useEffect(() => {
    const complete = turns.filter((turn) => turn.insight).slice(-20);
    try { localStorage.setItem(HISTORY_KEY, JSON.stringify(complete)); } catch { /* storage unavailable */ }
  }, [turns]);

  const ask = useCallback(async (q: string, viaVoice = false) => {
    if (!q.trim()) return;
    setInput("");
    // Conversation memory: send previous user turns so follow-ups
    // ("what about vehicle theft?") resolve against earlier context.
    const history: ConversationMessage[] = turnsRef.current
      .filter((turn) => turn.insight)
      .slice(-6)
      .flatMap((turn) => [
        { role: "user" as const, content: turn.q },
        { role: "assistant" as const, content: turn.insight!.answer },
      ]);
    // Stable per-turn id so a response always updates its own turn, even if the
    // user fires another question while this one is still loading.
    const id = ++idRef.current;
    setTurns((prev) => [...prev, { id, q, ts: Date.now(), loading: true }]);
    if (!aiConfigured()) {
      setTurns((prev) => prev.map((x) => (x.id === id ? { id, q, ts: x.ts, insight: textInsight(
        "The AI assistant isn't connected in this build. Set NEXT_PUBLIC_AI_FN_URL to your Catalyst Function endpoint to enable live answers. The rest of NETRA — cases, criminals, network, maps, analytics — works from the loaded records.",
        "demo-engine",
      ) } : x)));
      return;
    }
    try {
      // RAG first: retrieve the relevant case documents and answer grounded in
      // them. Fall back to a plain LLM answer if the knowledge base isn't set up.
      const request = {
        history,
        language: (lang === "kn" ? "kn" : "en") as "en" | "kn",
        via_voice: viaVoice,
      };
      const rag = await askRag(q, request);
      let insight: AiInsight;
      if (rag) {
        insight = ragInsight(rag.answer, rag.sources, rag.meta);
      } else {
        const response = await askAssistant(q, { system: NETRA_SYSTEM, ...request });
        if (response) {
          insight = textInsight(response.answer, "llm", response.meta);
        } else {
          const search = await searchCloudRecords(q, 8);
          insight = search?.hits?.length
            ? searchInsight(q, search.hits, search.warning)
            : textInsight("I could reach the AI Function, but it did not return a usable answer for this query. Try a case, FIR number, crime type, district, suspect, vehicle, or evidence term.", "demo-engine");
        }
      }
      setTurns((prev) => prev.map((x) => (x.id === id ? { id, q, ts: x.ts, insight } : x)));
    } catch {
      const search = await searchCloudRecords(q, 8).catch(() => null);
      const insight = search?.hits?.length
        ? searchInsight(q, search.hits, search.warning)
        : textInsight("NETRA could not complete this request. Check the Catalyst Function health and try again with an FIR number, district, offence, suspect, vehicle, or evidence term.", "demo-engine");
      setTurns((prev) => prev.map((x) => (x.id === id ? { id, q, ts: x.ts, insight } : x)));
    }
  }, [lang]);

  const prepareVoiceTranscript = useCallback(async (transcript: string) => {
    // Keep the captured command usable even when the optional Zia enrichment
    // call is unavailable or slow.
    setInput(transcript);
    setVoiceMsg("Analyzing command with Catalyst Zia...");
    const analyzed = await analyzeVoiceCommand(transcript);
    const command = analyzed?.text || transcript;
    setVoiceMsg(null);
    setInput(command);
  }, []);

  // Speech recognition creates the transcript; Catalyst Zia Text Analytics
  // processes it before the officer reviews and submits the command.
  const startWebSpeech = useCallback(() => {
    const SR = getSpeechRecognition();
    if (!SR) { setListening(false); return; }
    const rec = new SR();
    rec.lang = lang === "kn" ? "kn-IN" : "en-IN";
    rec.interimResults = true;
    rec.continuous = false;
    rec.onresult = (e) => {
      const results = Array.from(e.results as ArrayLike<ArrayLike<{ transcript: string }> & { isFinal: boolean }>);
      const transcript = results.map((r) => r[0]?.transcript ?? "").join(" ").trim();
      // Drop the transcript into the composer so the officer can review or edit
      // before hitting send — do NOT auto-submit.
      setInput(transcript);
      const last = results[results.length - 1];
      if (last?.isFinal && transcript) {
        setListening(false);
        void prepareVoiceTranscript(transcript);
      }
    };
    rec.onend = () => {
      setListening(false);
      recRef.current = null;
    };
    rec.onerror = (e) => {
      setListening(false);
      recRef.current = null;
      setVoiceMsg(speechErr(e?.error));
    };
    recRef.current = rec;
    setListening(true);
    setVoiceMsg(null);
    try {
      rec.start();
    } catch {
      recRef.current = null;
      setListening(false);
      setVoiceMsg("Could not start microphone recognition. Check this site's microphone permission and try again.");
    }
  }, [lang, prepareVoiceTranscript]);

  const startCloudRecording = useCallback(async () => {
    if (typeof navigator.mediaDevices?.getUserMedia !== "function" || typeof MediaRecorder === "undefined" || !getAudioContext()) {
      startWebSpeech();
      return;
    }
    try {
      setVoiceMsg("Allow microphone access, then speak your command.");
      const stream = await navigator.mediaDevices.getUserMedia({
        audio: { channelCount: 1, echoCancellation: true, noiseSuppression: true },
      });
      mediaStreamRef.current = stream;
      const preferred = ["audio/webm;codecs=opus", "audio/mp4", "audio/ogg;codecs=opus"]
        .find((type) => MediaRecorder.isTypeSupported(type));
      const recorder = preferred ? new MediaRecorder(stream, { mimeType: preferred }) : new MediaRecorder(stream);
      const chunks: Blob[] = [];
      recorder.ondataavailable = (event) => {
        if (event.data.size) chunks.push(event.data);
      };
      recorder.onerror = () => {
        setListening(false);
        setVoiceBusy(false);
        setVoiceMsg("Microphone recording failed. Check browser microphone permission and try again.");
      };
      recorder.onstop = async () => {
        if (recordTimerRef.current) clearTimeout(recordTimerRef.current);
        recordTimerRef.current = null;
        mediaStreamRef.current?.getTracks().forEach((track) => track.stop());
        mediaStreamRef.current = null;
        setListening(false);
        if (!chunks.length) {
          setVoiceMsg("No audio was captured. Check the selected microphone and try again.");
          return;
        }
        setVoiceBusy(true);
        setVoiceMsg("Transcribing with Catalyst Zia...");
        try {
          const recording = new Blob(chunks, { type: recorder.mimeType || preferred || "audio/webm" });
          const wav = await recordingToWav(recording);
          const audio = await blobToBase64(wav);
          const result = await transcribeAudio(audio, lang === "kn" ? "kn" : "en");
          if (!result?.text) {
            setVoiceMsg("Catalyst could not recognise speech. Speak clearly and try again.");
            return;
          }
          await prepareVoiceTranscript(result.text);
        } catch {
          setVoiceMsg("Voice processing failed. Check the Catalyst Function and try again.");
        } finally {
          setVoiceBusy(false);
        }
      };
      mediaRecorderRef.current = recorder;
      recorder.start(250);
      setListening(true);
      setVoiceMsg(null);
      recordTimerRef.current = setTimeout(() => {
        if (recorder.state === "recording") recorder.stop();
      }, 12000);
    } catch (error) {
      const name = error instanceof DOMException ? error.name : "";
      setListening(false);
      setVoiceMsg(
        name === "NotAllowedError"
          ? "Microphone permission denied. Allow microphone access for this site, then try again."
          : "No microphone is available. Check the browser input device and try again."
      );
    }
  }, [lang, prepareVoiceTranscript, startWebSpeech]);

  const toggleMic = useCallback(() => {
    if (voiceBusy) return;
    if (listening) {
      if (mediaRecorderRef.current?.state === "recording") {
        mediaRecorderRef.current.stop();
        return;
      }
      recRef.current?.stop();
      return;
    }
    if (!voiceSupported) {
      setVoiceMsg("Voice input needs microphone access in a current Chrome, Edge, Firefox, or Safari browser.");
      return;
    }
    // Keep localhost immediate for development. On deployed HTTPS builds,
    // record audio and send it through Catalyst Zia speech-to-text so the
    // production microphone path is owned by the configured Catalyst models.
    const localBrowser = window.location.hostname === "localhost" || window.location.hostname === "127.0.0.1";
    if (localBrowser && getSpeechRecognition()) {
      startWebSpeech();
      return;
    }
    void startCloudRecording();
  }, [listening, startCloudRecording, startWebSpeech, voiceBusy, voiceSupported]);

  // Scan an FIR document — Catalyst Zia OCR via the Function. Extracted text
  // drops into the ask box (and the Function stores the scan + result).
  const onScan = useCallback(async (file: File | null) => {
    if (!file) return;
    setScanning(true);
    try {
      const b64 = await blobToBase64(file);
      const res = await extractText(b64, lang === "kn" ? "kan" : "eng", file.name);
      if (res?.text) setInput((prev) => (prev ? `${prev}\n${res.text}` : res.text));
      else setInput("Could not read text from that document. Try a clearer scan.");
    } catch {
      setInput("Document scan failed — check the Catalyst Function / Zia OCR.");
    } finally {
      setScanning(false);
      if (fileRef.current) fileRef.current.value = "";
    }
  }, [lang]);

  const exportPdf = useCallback(async () => {
    setPdfBusy(true);
    try {
      const transcript = turnsRef.current.filter((turn) => turn.insight).map((turn) => ({
        question: turn.q,
        answer: turn.insight?.answer || "",
        audit_id: turn.insight?.explain.audit_id || "",
      }));
      const generated = await exportConversationPdf(transcript);
      if (!generated?.pdf) {
        window.print();
        return;
      }
      const binary = atob(generated.pdf);
      const bytes = new Uint8Array(binary.length);
      for (let index = 0; index < binary.length; index += 1) bytes[index] = binary.charCodeAt(index);
      const url = URL.createObjectURL(new Blob([bytes], { type: generated.mime || "application/pdf" }));
      const link = document.createElement("a");
      link.href = url;
      link.download = generated.filename || "netra-investigation.pdf";
      link.click();
      setTimeout(() => URL.revokeObjectURL(url), 1000);
    } finally {
      setPdfBusy(false);
    }
  }, []);

  // Auto-run a query passed via ?q= (from global search)
  useEffect(() => {
    const q = params.get("q");
    if (q) ask(q);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Newest result sits at the top of the feed, directly under the command bar —
  // keep the feed scrolled to the top when a new query lands.
  useEffect(() => {
    resultsRef.current?.scrollTo({ top: 0, behavior: "smooth" });
  }, [turns.length]);

  const empty = turns.length === 0;
  // Newest-first: an investigator reads the latest result, not the oldest.
  const ordered = useMemo(() => [...turns].reverse(), [turns]);
  const resultCount = turns.length;

  return (
    <div className="flex h-[calc(100vh-8.5rem)] flex-col print:block print:h-auto">
      {/* Header — aligned to the console PageHeader language */}
      <div className="mb-4 flex flex-wrap items-end justify-between gap-x-4 gap-y-3 border-b border-border/60 pb-4">
        <div className="flex min-w-0 items-stretch gap-3">
          <span aria-hidden className="w-[3px] shrink-0 self-stretch rounded-full bg-accent print:hidden" />
          <div className="min-w-0">
            <div className="flex items-center gap-2">
              <ScanSearch className="h-5 w-5 shrink-0 text-accent print:hidden" />
              <h1 className="font-display text-[1.5rem] font-bold leading-[1.08] tracking-[-0.03em] md:text-[1.7rem]">{t("assistant.title")}</h1>
            </div>
            <p className="mt-1 text-sm text-muted print:hidden">{t("assistant.subtitle")}</p>
            <p className="hidden text-sm text-muted print:block" suppressHydrationWarning>
              NETRA — Investigation query log · Karnataka State Police (demo)
            </p>
          </div>
        </div>
        <div className="flex w-full shrink-0 flex-wrap items-center gap-2 sm:w-auto print:hidden">
          <span className="chip border-success/30 bg-success/10 text-success" title="Catalyst QuickML with Cloud Scale record retrieval">
            <Cpu className="h-3 w-3" /> Catalyst Intelligence
          </span>
          {!empty && (
            <>
              <button
                onClick={() => { setTurns([]); localStorage.removeItem(HISTORY_KEY); }}
                className="btn-ghost"
                title="Clear saved conversation"
                aria-label="Clear conversation"
              >
                <History className="h-4 w-4" /> Clear
              </button>
              <button onClick={() => { void exportPdf(); }} disabled={pdfBusy} className="btn-ghost" title="Export query log as PDF">
                {pdfBusy ? <Loader2 className="h-4 w-4 animate-spin" /> : <FileDown className="h-4 w-4" />} {t("assistant.export")}
              </button>
            </>
          )}
        </div>
      </div>

      {/* ── Command console — the intelligence search / command interface ── */}
      <div className="print:hidden">
        <form
          onSubmit={(e) => { e.preventDefault(); ask(input); }}
          className={cn(
            "group relative rounded-lg border bg-surface shadow-[0_1px_2px_0_rgb(0_0_0/0.16)] transition-colors",
            listening ? "border-accent/60" : "border-border focus-within:border-accent/60",
          )}
        >
          <div className="flex items-center gap-1 border-b border-border/60 px-3.5 py-1.5">
            <Terminal className="h-3 w-3 text-accent" />
            <span className="eyebrow">Intelligence query</span>
            <span className="ml-auto hidden items-center gap-1 text-[10.5px] text-muted sm:flex">
              <Route className="h-3 w-3" /> English &amp; ಕನ್ನಡ · voice · document scan
            </span>
          </div>
          <div className="flex items-center gap-2 px-3 py-2.5">
            <Search className={cn("h-4 w-4 shrink-0", listening ? "text-accent" : "text-muted")} />
            <input
              ref={inputRef}
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder={listening ? "Listening… speak your query" : t("assistant.placeholder")}
              className="min-w-0 flex-1 bg-transparent text-[15px] text-fg outline-none placeholder:text-muted"
              aria-label="Investigation query"
            />
            {input && (
              <button
                type="button"
                onClick={() => { setInput(""); inputRef.current?.focus(); }}
                className="grid h-7 w-7 shrink-0 place-items-center rounded-md text-muted transition-colors hover:bg-elevated hover:text-fg"
                title="Clear"
                aria-label="Clear query"
              >
                <X className="h-3.5 w-3.5" />
              </button>
            )}
            <span className="mx-0.5 hidden h-6 w-px bg-border/70 sm:block" />
            <input
              ref={fileRef}
              type="file"
              accept="image/*"
              className="hidden"
              onChange={(e) => onScan(e.target.files?.[0] ?? null)}
            />
            <button
              type="button"
              onClick={() => fileRef.current?.click()}
              disabled={scanning}
              className={cn("grid h-9 w-9 shrink-0 place-items-center rounded-md border border-border bg-elevated/60 text-subtle transition-colors hover:border-accent/50 hover:text-fg", scanning && "text-accent")}
              title="Scan an FIR document (Zia OCR)"
              aria-label="Scan document"
            >
              {scanning ? <Loader2 className="h-4 w-4 animate-spin" /> : <ScanText className="h-4 w-4" />}
            </button>
            <button
              type="button"
              onClick={toggleMic}
              className={cn(
                "grid h-9 w-9 shrink-0 place-items-center rounded-md border border-border bg-elevated/60 text-subtle transition-colors hover:border-accent/50 hover:text-fg",
                listening && "border-accent/60 text-accent",
                voiceBusy && "border-accent/40 text-accent",
              )}
              title={listening ? "Stop listening" : `Voice command (${lang === "kn" ? "ಕನ್ನಡ" : "English"}) via Catalyst Zia speech and NLP`}
              aria-label="Voice input"
              aria-pressed={listening}
            >
              {voiceBusy ? <Loader2 className="h-4 w-4 animate-spin" /> : listening ? <MicOff className="h-4 w-4 animate-pulse" /> : <Mic className="h-4 w-4" />}
            </button>
            <button className="btn-accent h-9 shrink-0 px-4" disabled={!input.trim()} title="Run query">
              Run <ArrowRight className="h-4 w-4" />
              <span className="kbd ml-1 hidden border-accent-fg/20 bg-accent-fg/10 text-accent-fg/80 md:inline-flex">
                <CornerDownLeft className="h-3 w-3" />
              </span>
            </button>
          </div>
        </form>

        {/* Quick investigation tasks */}
        <div className="mt-2.5 flex flex-wrap items-center gap-1.5">
          <span className="stat-label mr-0.5">Quick queries</span>
          {TASKS.map((task) => (
            <button
              key={task.label}
              onClick={() => ask(task.q)}
              className="inline-flex items-center gap-1.5 rounded-md border border-border bg-elevated/50 px-2.5 py-1 text-xs font-medium text-subtle transition-colors hover:border-accent/50 hover:bg-elevated hover:text-fg"
              title={task.q}
            >
              <task.icon className="h-3.5 w-3.5 text-accent" /> {task.label}
            </button>
          ))}
        </div>

        {(listening || voiceBusy || voiceMsg) && (
          <p className={cn("mt-2 flex items-center gap-1.5 text-xs", voiceMsg ? "text-warning" : "text-accent")}>
            {(listening || voiceBusy) && <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-current" />}
            {voiceMsg || "Listening… speak now, then tap the mic again to stop."}
          </p>
        )}
      </div>

      {/* ── Results feed ── */}
      <div ref={resultsRef} className="mt-4 flex-1 space-y-4 overflow-y-auto pr-1 print:overflow-visible">
        {!empty && (
          <div className="flex items-center gap-2 print:hidden">
            <span className="stat-label">Query log</span>
            <span className="text-[11px] text-muted">{resultCount} result{resultCount === 1 ? "" : "s"} · newest first</span>
            <span className="h-px flex-1 bg-border/50" />
          </div>
        )}

        {empty ? (
          <EmptyState onPick={ask} />
        ) : (
          ordered.map((turn, i) => (
            <ResultRecord
              key={turn.id}
              turn={turn}
              index={resultCount - i}
              onAlt={ask}
              lang={lang}
            />
          ))
        )}
      </div>
    </div>
  );
}

/* ─────────────────────────── Empty / briefing state ─────────────────────── */

function EmptyState({ onPick }: { onPick: (q: string) => void }) {
  return (
    <div className="animate-fade-in space-y-4">
      <div className="card panel-pad">
        <div className="flex items-center gap-2">
          <FolderSearch className="h-4 w-4 text-accent" />
          <span className="stat-label text-fg">Start an investigation query</span>
        </div>
        <p className="mt-2 max-w-2xl text-sm leading-relaxed text-muted">
          Ask in natural language — English or ಕನ್ನಡ, typed or by voice. NETRA resolves the query
          against the case-file knowledge base and returns a structured, sourced result with a
          verifiable audit trail. Pick a starting point:
        </p>
        <div className="mt-4 grid min-w-0 grid-cols-1 gap-2 sm:grid-cols-2">
          {EXAMPLES.map((ex) => (
            <button
              key={ex.q}
              onClick={() => onPick(ex.q)}
              className="lift-row group flex min-w-0 items-center gap-3 rounded-lg border border-border/70 bg-elevated/40 px-3.5 py-3 text-left hover:bg-elevated/70"
            >
              <span className="grid h-8 w-8 shrink-0 place-items-center rounded-md border border-border/60 bg-surface/60 transition-colors group-hover:border-accent/40">
                <ex.icon className="h-4 w-4 text-accent" />
              </span>
              <span className="min-w-0">
                <span className="block truncate text-sm font-medium text-fg">{ex.q}</span>
                <span className="block text-[11px] text-muted">{ex.hint}</span>
              </span>
              <ChevronRight className="ml-auto h-4 w-4 shrink-0 text-muted transition-colors group-hover:text-accent" />
            </button>
          ))}
        </div>
      </div>
      <div className="flex items-start gap-2.5 rounded-lg border border-border/70 bg-elevated/40 p-3.5 text-xs leading-relaxed text-muted">
        <ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-accent" />
        <span>
          Every query follows role checks, validated retrieval, evidence verification, and immutable audit logging.
          The investigating officer remains responsible for every operational decision.
        </span>
      </div>
    </div>
  );
}

/* ─────────────────────────── Result record (per query) ──────────────────── */

function ResultRecord({ turn, index, onAlt, lang }: { turn: Turn; index: number; onAlt: (q: string) => void; lang: string }) {
  return (
    <section className="card animate-fade-in overflow-hidden">
      {/* Query header strip — dossier record marker + question */}
      <header className="flex items-start gap-3 border-b border-border/60 bg-elevated/40 px-4 py-3">
        <span
          className="mt-0.5 inline-flex shrink-0 items-center rounded border border-border bg-surface px-1.5 py-0.5 font-mono text-[11px] font-semibold text-muted tabular-nums"
          title={`Query record ${index}`}
        >
          {String(index).padStart(2, "0")}
        </span>
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-[0.16em] text-muted">
            <Search className="h-3 w-3 text-accent" /> Query
            <span className="font-mono font-normal normal-case tracking-normal text-muted/70">· {fmtTime(turn.ts)}</span>
          </div>
          <p className="mt-1 text-[15px] font-semibold leading-snug text-fg">{turn.q}</p>
        </div>
      </header>

      <div className="px-4 py-4">
        {turn.loading ? (
          <LoadingResult />
        ) : turn.insight ? (
          <InsightBody insight={turn.insight} onAlt={onAlt} lang={lang} />
        ) : (
          <div className="flex items-center gap-2 rounded-md border border-danger/30 bg-danger/10 px-3.5 py-3 text-sm text-danger">
            <AlertTriangle className="h-4 w-4 shrink-0" /> The query could not be completed. Check the connection and try again.
          </div>
        )}
      </div>
    </section>
  );
}

function LoadingResult() {
  return (
    <div className="space-y-4">
      <div className="flex items-center gap-2 text-sm text-muted">
        <Loader2 className="h-4 w-4 animate-spin text-accent" /> Retrieving case documents &amp; reasoning over records…
      </div>
      <div>
        <div className="stat-label mb-2">Investigation summary</div>
        <div className="space-y-2" aria-hidden>
          <div className="skeleton h-3 w-full" />
          <div className="skeleton h-3 w-11/12" />
          <div className="skeleton h-3 w-4/5" />
        </div>
      </div>
      <div className="grid gap-2 sm:grid-cols-2" aria-hidden>
        <div className="skeleton h-16 w-full" />
        <div className="skeleton h-16 w-full" />
      </div>
    </div>
  );
}

/* Inline renderer: bold, code, and highlighted / inspectable FIR references. */
function renderInline(text: string, onFir?: (fir: string) => void): React.ReactNode[] {
  const nodes: React.ReactNode[] = [];
  const re = /\*\*([^*]+)\*\*|`([^`]+)`|\b(?:FIR[\s.:#-]*)?(\d{15,18})\b/g;
  let last = 0;
  let key = 0;
  let m: RegExpExecArray | null;
  while ((m = re.exec(text))) {
    if (m.index > last) nodes.push(<Fragment key={key++}>{text.slice(last, m.index)}</Fragment>);
    if (m[1] != null) {
      nodes.push(<strong key={key++} className="font-semibold text-fg">{m[1]}</strong>);
    } else if (m[2] != null) {
      nodes.push(<code key={key++} className="rounded bg-elevated px-1 py-0.5 font-mono text-[0.85em] text-accent">{m[2]}</code>);
    } else if (m[3] != null) {
      const fir = m[3];
      nodes.push(
        <button
          key={key++}
          type="button"
          onClick={() => onFir?.(fir)}
          title="Inspect this case"
          className="mx-px inline-flex items-center gap-0.5 rounded border border-accent/30 bg-accent/10 px-1 font-mono text-[0.82em] font-medium text-accent align-baseline transition-colors hover:border-accent/60 hover:bg-accent/20 print:border-none print:bg-transparent print:p-0"
        >
          <Hash className="h-2.5 w-2.5 print:hidden" />{fir}
        </button>,
      );
    }
    last = re.lastIndex;
  }
  if (last < text.length) nodes.push(<Fragment key={key++}>{text.slice(last)}</Fragment>);
  return nodes;
}

function InsightBody({ insight, onAlt, lang }: { insight: AiInsight; onAlt: (q: string) => void; lang: string }) {
  const [showTech, setShowTech] = useState(false);
  const [showData, setShowData] = useState(false);
  const [showSql, setShowSql] = useState(false);
  const [speaking, setSpeaking] = useState(false);
  const [kannada, setKannada] = useState<string | null>(null);
  const [translating, setTranslating] = useState(false);
  const audioRef = useRef<HTMLAudioElement | null>(null);
  const e = insight.explain;
  const pct = Math.round(e.confidence * 100);
  const confTone = pct >= 80 ? "success" : pct >= 60 ? "warning" : "muted";
  const confColor = confTone === "success" ? "text-success" : confTone === "warning" ? "text-warning" : "text-muted";

  const display = kannada ?? insight.answer;
  const blocks = useMemo<AnswerBlock[]>(() => parseBlocks(display), [display]);
  const findings = useMemo(() => keyFindings(blocks), [blocks]);
  const firs = useMemo(() => extractFirs(insight.answer), [insight.answer]);
  // Prose = paragraphs + any genuine sub-headings, minus headings that just echo
  // our own section labels (Investigation Summary / Key Findings / …).
  const proseBlocks = blocks.filter(
    (b): b is Exclude<AnswerBlock, { kind: "list" }> =>
      b.kind !== "list" && !(b.kind === "heading" && SECTION_ECHO.test(b.text.trim())),
  );
  const hasProse = proseBlocks.length > 0;

  // Read aloud via Catalyst Zia TTS; fall back to the browser voice if the
  // Function/Zia is unavailable. Speech is a concise, naturalised version —
  // never raw Markdown, no FIR numbers / audit IDs / metadata read aloud.
  const speak = useCallback(async () => {
    if (speaking) {
      audioRef.current?.pause();
      if (typeof window !== "undefined" && "speechSynthesis" in window) window.speechSynthesis.cancel();
      setSpeaking(false);
      return;
    }
    const speakLang: "en" | "kn" = kannada ? "kn" : lang === "kn" ? "kn" : "en";
    const spoken = naturalizeForSpeech(kannada ?? insight.answer, speakLang);
    const bcp = speakLang === "kn" ? "kn-IN" : "en-IN";
    setSpeaking(true);
    const b64 = await synthesizeSpeech(spoken, bcp);
    if (b64) {
      const audio = new Audio(b64.startsWith("data:") ? b64 : `data:audio/wav;base64,${b64}`);
      audioRef.current = audio;
      audio.onended = () => setSpeaking(false);
      audio.onerror = () => setSpeaking(false);
      audio.play().catch(() => setSpeaking(false));
      return;
    }
    if (typeof window !== "undefined" && "speechSynthesis" in window) {
      const u = new SpeechSynthesisUtterance(spoken);
      u.lang = bcp;
      u.onend = () => setSpeaking(false);
      u.onerror = () => setSpeaking(false);
      window.speechSynthesis.cancel();
      window.speechSynthesis.speak(u);
      return;
    }
    setSpeaking(false);
  }, [insight.answer, kannada, lang, speaking]);

  // Translate the answer to Kannada via Catalyst Zia.
  const translate = useCallback(async () => {
    if (kannada) { setKannada(null); return; }
    setTranslating(true);
    const kn = await translateText(insight.answer, "kn", "en");
    setKannada(kn);
    setTranslating(false);
  }, [insight.answer, kannada]);

  const hasSources = (insight.sources?.length ?? 0) > 0;
  const hasEvidenceStrings = !hasSources && e.evidence.length > 0;

  return (
    <div className="space-y-4">
      {/* Result toolbar: status + actions */}
      <div className="flex flex-wrap items-center gap-2">
        <span className="chip border-accent/30 bg-accent/10 text-accent">
          <Database className="h-3 w-3" /> {SOURCE_LABEL[e.source] || e.source}
        </span>
        <span className={cn("inline-flex items-center gap-1.5 rounded-md border px-2 py-0.5 text-xs font-medium",
          confTone === "success" ? "border-success/30 bg-success/10 text-success"
          : confTone === "warning" ? "border-warning/30 bg-warning/10 text-warning"
          : "border-border text-muted")}>
          <BadgeCheck className="h-3 w-3" /> Confidence {pct}%
        </span>
        <div className="ml-auto flex items-center gap-1">
          <button
            onClick={translate}
            disabled={translating}
            className={cn("inline-flex items-center gap-1.5 rounded-md border border-border px-2 py-1 text-xs font-medium text-muted transition-colors hover:border-accent/50 hover:text-fg disabled:opacity-50 print:hidden", kannada && "border-accent/50 text-accent")}
            title={kannada ? "Show English" : "Translate to Kannada (ಕನ್ನಡ)"}
          >
            {translating ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : kannada ? "EN" : "ಕನ್ನಡ"}
          </button>
          <button
            onClick={speak}
            className={cn("inline-flex items-center gap-1.5 rounded-md border border-border px-2 py-1 text-xs font-medium text-muted transition-colors hover:border-accent/50 hover:text-fg print:hidden", speaking && "border-accent/50 text-accent")}
            title={speaking ? "Stop reading" : "Read a concise summary aloud"}
          >
            <Volume2 className={cn("h-3.5 w-3.5", speaking && "animate-pulse")} /> {speaking ? "Stop" : "Listen"}
          </button>
        </div>
      </div>

      {/* Investigation Summary — shown when there is prose, or when there is
          nothing else structured to fall back on. List-only answers skip this
          and are carried entirely by Key Findings. */}
      {(hasProse || findings.length === 0) && (
        <div>
          <SectionLabel icon={FileText}>Investigation summary</SectionLabel>
          <div className="mt-2 space-y-2.5 text-[15px] leading-relaxed text-subtle">
            {hasProse ? (
              proseBlocks.map((b, i) =>
                b.kind === "heading" ? (
                  <h4 key={i} className="pt-1 text-[11px] font-semibold uppercase tracking-[0.12em] text-muted">{renderInline(b.text, (f) => onAlt(`Tell me about case ${f}`))}</h4>
                ) : (
                  <p key={i}>{renderInline(b.text, (f) => onAlt(`Tell me about case ${f}`))}</p>
                ),
              )
            ) : (
              <p>{kannada ?? <Translated text={insight.answer} />}</p>
            )}
          </div>
        </div>
      )}

      {/* Key Findings */}
      {findings.length > 0 && (
        <div>
          <SectionLabel icon={ListChecks}>Key findings</SectionLabel>
          <ul className="mt-2 space-y-1.5">
            {findings.map((f, i) => (
              <li key={i} className="flex gap-2.5 text-sm leading-relaxed text-subtle">
                <span aria-hidden className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-[2px] bg-accent/70" />
                <span>{renderInline(f, (fir) => onAlt(`Tell me about case ${fir}`))}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Related FIRs / Cases */}
      {firs.length > 0 && (
        <div>
          <SectionLabel icon={FolderSearch}>Related FIRs / cases</SectionLabel>
          <div className="mt-2 flex flex-wrap gap-1.5">
            {firs.map((fir) => (
              <button
                key={fir}
                onClick={() => onAlt(`Tell me about case ${fir}`)}
                className="inline-flex items-center gap-1.5 rounded-md border border-border bg-elevated/50 px-2.5 py-1.5 font-mono text-xs font-medium text-subtle transition-colors hover:border-accent/50 hover:text-accent"
                title="Inspect this case"
              >
                <Hash className="h-3 w-3 text-accent" />{fir}
                <ChevronRight className="h-3 w-3 opacity-50" />
              </button>
            ))}
          </div>
        </div>
      )}

      {/* Evidence & Sources */}
      {(hasSources || hasEvidenceStrings) && (
        <div>
          <SectionLabel icon={Database}>{e.source === "rag" ? "Evidence & source documents" : "Records used"}</SectionLabel>
          {hasSources ? (
            <div className="mt-2 grid gap-2 sm:grid-cols-2">
              {insight.sources!.map((s, i) => (
                <div key={i} className="rounded-md border border-border bg-elevated/40 p-3 transition-colors hover:border-accent/40">
                  <div className="flex items-start gap-2">
                    <FileText className="mt-0.5 h-3.5 w-3.5 shrink-0 text-accent" />
                    <div className="min-w-0 flex-1">
                      <div className="truncate text-xs font-semibold text-fg" title={s.title || `Source ${i + 1}`}>
                        {s.title || `Source document ${i + 1}`}
                      </div>
                      {s.snippet && <p className="mt-1 line-clamp-3 text-[11.5px] leading-relaxed text-muted">{s.snippet}</p>}
                    </div>
                    {typeof s.score === "number" && (
                      <span className="shrink-0 rounded border border-border px-1 font-mono text-[10px] text-muted" title="Retrieval relevance score">
                        {s.score.toFixed(2)}
                      </span>
                    )}
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div className="mt-2 flex flex-wrap gap-1.5">
              {e.evidence.map((ev, i) => (
                <span key={i} className="chip font-mono text-[10.5px]">{ev}</span>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Chart (when a template/SQL answer carries series data) */}
      {insight.chart && insight.rows && insight.rows.length > 1 && (
        <div>
          <SectionLabel icon={GitCompare}>Visualisation</SectionLabel>
          <div className="mt-2 rounded-md border border-border bg-elevated/40 p-3">
            {insight.chart.kind === "line" ? (
              <TrendLine data={insight.rows} x={insight.chart.x} y={insight.chart.y} height={200} />
            ) : (
              <BarSeries data={insight.rows.slice(0, 12)} x={insight.chart.x} y={insight.chart.y} height={220} />
            )}
          </div>
        </div>
      )}

      {/* Verification */}
      <div className="rounded-lg border border-border/70 bg-elevated/30 p-3.5">
        <div className="flex items-center gap-1.5">
          <ShieldCheck className="h-3.5 w-3.5 text-accent" />
          <span className="text-[11px] font-semibold uppercase tracking-[0.12em] text-muted">Verification</span>
        </div>
        <p className="mt-2 text-sm leading-relaxed text-muted">{e.reasoning}</p>
        <div className="mt-3 flex flex-wrap items-center gap-x-5 gap-y-2 text-xs">
          <span className="flex items-center gap-1.5">
            <span className="text-muted">Confidence</span>
            <span className="h-1.5 w-20 overflow-hidden rounded-full bg-surface ring-1 ring-inset ring-border/60">
              <span className={cn("block h-full rounded-full", confTone === "success" ? "bg-success" : confTone === "warning" ? "bg-warning" : "bg-muted")} style={{ width: `${pct}%` }} />
            </span>
            <span className={cn("font-mono font-semibold tabular-nums", confColor)}>{pct}%</span>
          </span>
          <span className="text-muted">Records used <span className="font-mono text-subtle">{e.records_used}</span></span>
          {e.context_used && e.context_used.length > 0 && (
            <span className="flex items-center gap-1.5 text-muted">
              <History className="h-3 w-3" /> Context:
              {e.context_used.map((c, i) => <span key={i} className="font-mono text-info">{c}</span>)}
            </span>
          )}
        </div>
      </div>

      {/* Follow-up */}
      {e.alternatives.length > 0 && (
        <div className="print:hidden">
          <SectionLabel icon={Search}>Follow-up queries</SectionLabel>
          <div className="mt-2 flex flex-wrap gap-1.5">
            {e.alternatives.map((a, i) => (
              <button
                key={i}
                onClick={() => onAlt(a)}
                className="inline-flex items-center gap-1.5 rounded-md border border-border/70 bg-elevated/40 px-2.5 py-1.5 text-xs text-subtle transition-colors hover:border-accent/50 hover:text-fg"
              >
                {a} <ArrowRight className="h-3 w-3 opacity-50" />
              </button>
            ))}
          </div>
        </div>
      )}

      {/* Technical details — subtle, collapsed by default */}
      <div className="border-t border-border/50 pt-3 print:hidden">
        <button
          onClick={() => setShowTech((s) => !s)}
          className="flex w-full items-center gap-1.5 text-[11px] font-medium uppercase tracking-[0.1em] text-muted transition-colors hover:text-subtle"
        >
          <Cpu className="h-3 w-3" /> Technical details
          <ChevronDown className={cn("ml-auto h-3.5 w-3.5 transition-transform", showTech && "rotate-180")} />
        </button>
        {showTech && (
          <div className="mt-3 space-y-3 animate-fade-in">
            <dl className="grid grid-cols-2 gap-x-4 gap-y-2 text-xs sm:grid-cols-3">
              <TechItem label="Routing"><span className="text-subtle">{routeLabel(e.ai_model)}</span></TechItem>
              <TechItem label="Source"><span className="text-subtle">{SOURCE_LABEL[e.source] || e.source}</span></TechItem>
              <TechItem label="Latency"><span className="font-mono text-subtle">{e.processing_ms} ms</span></TechItem>
              <TechItem label="Records used"><span className="font-mono text-subtle">{e.records_used}</span></TechItem>
              <TechItem label="Execution"><span className="inline-flex items-center gap-1 text-subtle"><Cpu className="h-3 w-3" /> {engineScope(e.source)}</span></TechItem>
              <TechItem label="Audit ID"><span className="font-mono text-subtle">{e.audit_id}</span></TechItem>
            </dl>

            {insight.rows && insight.rows.length > 0 && (
              <div>
                <button onClick={() => setShowData((s) => !s)} className="flex items-center gap-1 text-[11px] font-medium text-subtle hover:text-fg">
                  <ChevronDown className={cn("h-3.5 w-3.5 transition-transform", showData && "rotate-180")} />
                  {showData ? "Hide" : "Show"} result table ({insight.rows.length} rows)
                </button>
                {showData && (
                  <div className="mt-2 max-h-72 overflow-auto rounded-lg border border-border">
                    <table className="w-full text-left text-xs">
                      <thead className="sticky top-0 bg-elevated">
                        <tr>
                          {insight.columns?.map((c) => (
                            <th key={c} className="whitespace-nowrap px-3 py-2 font-medium text-muted">{c}</th>
                          ))}
                        </tr>
                      </thead>
                      <tbody>
                        {insight.rows.slice(0, 50).map((r, i) => (
                          <tr key={i} className="border-t border-border/50">
                            {insight.columns?.map((c) => (
                              <td key={c} className="whitespace-nowrap px-3 py-1.5 font-mono text-subtle">{String(r[c] ?? "")}</td>
                            ))}
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}
              </div>
            )}

            {insight.sql && (
              <div>
                <button onClick={() => setShowSql((s) => !s)} className="flex items-center gap-1 text-[11px] font-medium text-subtle hover:text-fg">
                  <ChevronDown className={cn("h-3.5 w-3.5 transition-transform", showSql && "rotate-180")} />
                  {showSql ? "Hide" : "Show"} generated SQL
                </button>
                {showSql && (
                  <pre className="mt-2 overflow-x-auto rounded-lg border border-border bg-bg p-3 font-mono text-[11px] leading-relaxed text-subtle">
                    {insight.sql}
                  </pre>
                )}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

function SectionLabel({ icon: Icon, children }: { icon: typeof FileText; children: React.ReactNode }) {
  return (
    <div className="flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-[0.12em] text-muted">
      <Icon className="h-3.5 w-3.5 text-accent" /> {children}
    </div>
  );
}

function TechItem({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="min-w-0">
      <dt className="text-[10px] uppercase tracking-[0.1em] text-muted/70">{label}</dt>
      <dd className="mt-0.5 truncate">{children}</dd>
    </div>
  );
}
